services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 8000:8000  # Remove if you do not intend to use Edge Agents
    networks:
      yams_network:
        ipv4_address: 172.60.0.19
      server-network:

volumes:
  portainer_data:
    name: portainer_data
  

networks:
  yams_network:
    external: true
  server-network:
      external: true

